name: CI - Flower Model Pipeline

on:
  push:
    branches: [ main, feature_manjusha ]
  pull_request:
    branches: [ main, feature_manjusha ]

jobs:
  build-train-evaluate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: PoC/Model-Pipeline/himas-model-pipeline

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install hatchling
          pip install .

      - name: Run Flower Simulation
        run: |
          flwr run . --num-rounds=1

      - name: Evaluate Model
        run: |
          python evaluate_model.py

      - name: Upload Model and Metrics
        uses: actions/upload-artifact@v4
        with:
          name: trained-model-and-results
          path: |
            PoC/Model-Pipeline/himas-model-pipeline/models/
            PoC/Model-Pipeline/himas-model-pipeline/evaluation_results/

